-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.parthnerproducts
(
    parthnerproductsid integer NOT NULL,
    productnameid integer NOT NULL,
    partnerid integer NOT NULL,
    quantity integer NOT NULL,
    saledate date NOT NULL,
    CONSTRAINT parthnerproducts_pkey PRIMARY KEY (parthnerproductsid)
);

CREATE TABLE IF NOT EXISTS public.partners
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Type" character varying COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    "Director" character varying COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "Phone" character varying COLLATE pg_catalog."default" NOT NULL,
    "Address" character varying COLLATE pg_catalog."default" NOT NULL,
    "Inn" character varying COLLATE pg_catalog."default" NOT NULL,
    "Rating" integer NOT NULL,
    CONSTRAINT partners_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.productname
(
    productnameid integer NOT NULL,
    productname character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT productname_pkey PRIMARY KEY (productnameid)
);

CREATE TABLE IF NOT EXISTS public.products
(
    productid integer NOT NULL,
    producttypeid integer NOT NULL,
    productname integer NOT NULL,
    articlenumber character varying COLLATE pg_catalog."default" NOT NULL,
    minpartnerprice numeric(15, 2) NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (productid)
);

CREATE TABLE IF NOT EXISTS public.producttypes
(
    producttypeid integer NOT NULL,
    typename character varying COLLATE pg_catalog."default" NOT NULL,
    typecoefficient numeric(10, 2) NOT NULL,
    CONSTRAINT producttypes_pkey PRIMARY KEY (producttypeid)
);

ALTER TABLE IF EXISTS public.parthnerproducts
    ADD CONSTRAINT parthnerproducts_partnerid_fkey FOREIGN KEY (partnerid)
    REFERENCES public.partners ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.parthnerproducts
    ADD CONSTRAINT parthnerproducts_productnameid_fkey FOREIGN KEY (productnameid)
    REFERENCES public.productname (productnameid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_productname_fkey FOREIGN KEY (productname)
    REFERENCES public.productname (productnameid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_producttypeid_fkey FOREIGN KEY (producttypeid)
    REFERENCES public.producttypes (producttypeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;